### ISSUE TITLE
'utf-8' codec can't decode byte 0xd5 in position 94

### ISSUE THREAD

**Issue by P0Zeratul** [wenqihuang/LS-Net-Dynamic-MRI#3]
Hi,I'm a graduate student from China.When I tried to run your code an error occupied that says "'utf-8' codec can't decode byte 0xd5 in position 94".
Could you tell me what's going wrong and how to address this problem?
Thanks

**Comment by wenqihuang** [comment]
Hi P0Zeratul, 
sorry for the late reply. I can not reproduce the error in my local machine. Could you post the full error message and your running environment so that I can try to reproduce it? Many thanks!
Best,
Wenqi

**Comment by P0Zeratul** [comment]
Dear Dr.Wen,I've alread known how the error occurred and adressed it.Now I want to use other mult-coil datasets to train the network myself. Could you please upload the code of the ESPIRiT algorithm that calculates coil sense?

**Comment by P0Zeratul** [comment]
I used the method in create_dummy_data(I'm using Windows not Ubuntu, so I used another method instead of bart to generate the sence map, the other steps and the results are same). 

![image](https://user-images.githubusercontent.com/104356866/179430595-1593623f-0ebd-4ba9-9f96-e88d6398bd9e.png)
![image](https://user-images.githubusercontent.com/104356866/179430607-239222b9-4477-4dc9-ba0e-27a7955fd6b0.png)
![image](https://user-images.githubusercontent.com/104356866/179430610-f9c20048-0274-4a75-b5e2-04b071fcb4f4.png)
![image](https://user-images.githubusercontent.com/104356866/179430615-5cdf90e3-daf4-433a-89dd-ec4a765c5f4b.png)

But when I started the program, an error occurred. After the traceback list, it said:

    x = tf.transpose(x, perm=[0,1,2,4,3]) # permute a to make nx dimension the last one.
tensorflow.python.framework.errors_impl.ResourceExhaustedError: Exception encountered when calling layer "ls_cell_learned_step_2" (type LSCell_learned_step).

OOM when allocating tensor with shape[1,16,18,192,192] and type complex64 on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Transpose]

Call arguments received:
  • data=['tf.Tensor(shape=(1, 18, 36864), dtype=complex64)', 'tf.Tensor(shape=(1, 18, 36864), dtype=complex64)', 'tf.Tensor(shape=(1, 18, 36864), dtype=complex64)', 'tf.Tensor(shape=(1, 16, 18, 192, 192), dtype=complex64)', 'tf.Tensor(shape=(1, 16, 1, 192, 192), dtype=complex64)']
  • input_shape=TensorShape([1, 16, 18, 192, 192])

**Comment by wenqihuang** [comment]
Hi P0Zeratul,

glad to hear that you have solved the first problem! 

Regarding the ESPIRiT code, I just used the bart command `bart ecalib kspace sensitivity -t threshold`, which is back-ended by ESPIRiT. No complicated code involved for sensitivity map estimaton ;)

The OOM error you encountered means you are running out of GPU memory. Please consider reducing the model size (for example `n_iter`, `n_features` for convolution layers etc.) or/and compress the data into fewer coils. Of course switch to GPUs with more memory (48GB GPU memory works fine for my experiments) would also solve the problem :D. Good luck!

Best,
Wenqi

**Comment by dameimo** [comment]
> Hi,I'm a graduate student from China.When I tried to run your code an error occupied that says "'utf-8' codec can't decode byte 0xd5 in position 94". Could you tell me what's going wrong and how to address this problem? Thanks

Hi P0Zeratul，I am a graduate student from China, sorry to bother you. I have the same problem with you now, and I would like to ask for your advice. I wonder if it is convenient for you to leave your email address. Thank you very much!

**Comment by wenqihuang** [comment]
> > Hi,I'm a graduate student from China.When I tried to run your code an error occupied that says "'utf-8' codec can't decode byte 0xd5 in position 94". Could you tell me what's going wrong and how to address this problem? Thanks
> 
> Hi P0Zeratul，I am a graduate student from China, sorry to bother you. I have the same problem with you now, and I would like to ask for your advice. I wonder if it is convenient for you to leave your email address. Thank you very much!

Hi @dameimo ,

Would you post the error message here so that I can also try to fix it? Many thanks!

Best,
Wenqi

**Comment by P0Zeratul** [comment]
Hello dear doctor.I've already solved the problem I met.Here I wonder how to get the number of the trained model's parameters in tensorboard or somewhere else.

**Comment by wenqihuang** [comment]
Hi @P0Zeratul,
model parameter number is calculated in [this line](https://github.com/wenqihuang/LS-Net-Dynamic-MRI/blob/d0694bd6aca2d8a7784b494dc9ef6bab46add53e/main.py#L168) and outputed in terminal with [this line](https://github.com/wenqihuang/LS-Net-Dynamic-MRI/blob/d0694bd6aca2d8a7784b494dc9ef6bab46add53e/main.py#L171) of code. 
Best,
Wenqi

**Comment by wenqihuang** [comment]
Issue closed because the original problem has been solve. Feel free to open a new issue if you have further questions.

**Comment by P0Zeratul** [comment]
Thanks Dr.
