### ISSUE TITLE
Coil sensitivity maps estimation

### ISSUE THREAD

**Issue by yhao-z** [wenqihuang/LS-Net-Dynamic-MRI#8]
我看到您文章中提到多线圈数据是需要线圈敏感度的，而线圈敏感度 csm 是通过 ESPIRiT 方法进行估计的，而ESPIRiT方法估计线圈敏感度需要有自校准数据（低频全采样的数据）。

对于训练数据（全采样）这往往很容易估计。但是我看到您文章中进行了 prospective 的实验（论文3.2.4节），并且是用的 OCMR 数据集进行的实验。论文所用的 9x 欠采样数据的欠采样模板是**VISTA**，从您论文中对VISTA的描述中发现VISTA是没有自校准区域的获取的。

想问一下，您 prospective 实验中数据的线圈敏感度是如何获取的呢？

非常感谢！希望您百忙之中能够抽空回复下，感激不尽！

**Comment by wenqihuang** [comment]
Hello,

You are correct about the VISTA sampling pattern. In Cardiac MR, we usually assume that the coil sensitivity doesn't change significantly during the acquisition. This assumption allows us to perform averaging over the time dimension to build a fully sampled k-space (or near fully sampled). Then, we use its center as the ACS (Auto-Calibration Signal) area to estimate the coil sensitivity maps.

I hope this answers your question.

Best regards,
Wenqi

**Comment by yhao-z** [comment]
Thank u!! perfectly solved!
